// Auto-generated by export_xgb_js_model.py
export const XGB_FEATURES = ["totalRepeat", "unreachable", "totalVisits", "sequenceLength", "remainingCells", "avgValue", "valueVariance", "valueRange", "avgRow", "avgCol", "positionSpread", "columnSpan", "rowSpan", "depth", "allowStacking", "minVisits", "maxVisits", "minRepeat", "maxRepeat", "crossSequencesIndex", "notStackingRemainCells", "lengthRepeatProduct", "lengthSpreadProduct", "repeatSpreadProduct", "rowSpreadProduct", "logLength", "logTotalRepeat", "logPositionSpread", "sqrtLength", "sqrtTotalRepeat", "sqrtPositionSpread", "repeatDensity", "spanEfficiency", "positionConcentration"];
export const XGB_TREES = [];

export function xgbPredict(featureMap) {
  return 0;
}
